[package]
name = "aoc2019"
version = "0.1.0"
authors = ["David Szotten <davidszotten@gmail.com>"]
edition = "2018"

[dependencies]
clap = "*"
failure = "*"
itertools = "*"
regex = "*"
lazy_static = "*"
cached = "*"
